<a href="https://colab.research.google.com/github/aniranursyifa7-jpg/algoritma/blob/main/pandas_3_anira_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#P1

#running pandas dan numpy

import pandas as pd

import numpy as np


#menampilkan array 1-dimensi

ds = pd.Series([2, 4, 6, 8, 10])

print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [16]:
#P2
data = pd.Series(['a', 'b', 'c'])
npl = np.array(['x', 'y', 'x'])
data_np = pd.Series(npl)


print(data)

print(data_np)


#mengatur indeks pada numpy array data-np di atas

data_np = pd.Series(npl, index=[2,3,4])

print(data_np)

0    a
1    b
2    c
dtype: object
0    x
1    y
2    x
dtype: object
2    x
3    y
4    x
dtype: object

In [17]:
#P3 contoh operasi

ds1 = pd.Series([2, 4, 6, 8, 10])

ds2 = pd.Series([1, 3, 5, 7, 9])

dsa = ds1 + ds2  #operasi jumlah

dsb = ds1 - ds2

dsc = ds1 * ds2

dsd = ds1 / ds2

print(dsa)

print(dsb)

print(dsc)

print(dsd)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [18]:
#P4 konver pandas module Series ke python list

import pandas as pd

ds = pd.Series([2, 4, 6, 8, 10])

print("Pandas Series dan type")

print(ds)

print(type(ds))


print("Konver Pandas Series ke Python list")

print(ds.tolist())

print(type(ds.tolist()))

Pandas Series dan type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Konver Pandas Series ke Python list
[2, 4, 6, 8, 10]
<class 'list'>

In [19]:
#P5 convert a NumPy array to a Pandas series

import numpy as np

import pandas as pd

np_array = np.array([0, 20, 30, 40, 50])

print("NumPy array:")

print(np_array)


new_np = pd.Series(np_array)

print("konversi Pandas series:")

print(new_np)

NumPy array:
[ 0 20 30 40 50]
konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64

In [20]:
import pandas as pd

import numpy as np


#generate angka random

num_state = np.random.RandomState(100000)

num_series = pd.Series(num_state.normal(10, 4, 20, ))


print(num_series)

#print(num_state)

0     10.287026
1      2.607411
2     16.060083
3      9.957853
4      8.514146
5      7.330132
6     10.240599
7      8.301784
8      5.743568
9     -2.453565
10    10.966217
11    12.818131
12     6.844244
13     9.252506
14     7.808512
15    16.998639
16    12.540755
17     7.712178
18     7.101127
19    18.176767
dtype: float64

In [21]:
#P7.1 load data dari folder yang sama dengan coding

df = pd.read_csv('penjualan.csv')

df

# Boleh menampilkan sesuai selera

# df.head(4) > tampil 4 baris pertama

# df.tail(5)  > tampil 5 baris terakhir
#df.info()
df.describe()

             jan         feb         mar         apr
count   10.00000   10.000000   10.000000   10.000000
mean   187.00000  220.900000  165.500000  135.000000
std     81.14459   80.161573   83.081285   71.608504
min     95.00000  130.000000   75.000000   45.000000
25%    126.25000  160.000000  102.500000   77.500000
50%    175.00000  207.500000  142.500000  127.500000
75%    237.50000  262.500000  218.750000  182.500000
max    320.00000  374.000000  300.000000  270.000000

In [23]:
#P7.1 load data dari folder yang sama dengan coding percobaan

df = pd.read_csv('dataset_fiskal_97_hipoFull.csv')

#df.head(500)
# df.tail(500)
#df.info()
df.describe()

,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,ICT,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
count,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,...,1067.000000,1067.00000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2019.000000,107.905464,71.138960,53.830628,178.029850,107.452034,107.783393,106.766401,215.204077,81.898013,...,172.587882,173.69358,174.611565,172.471546,171.014255,12.538519,6.466692,0.398641,72.378847,4.958547
std,3.163761,57.856235,42.449883,28.680751,87.999498,54.994876,56.152152,56.852234,110.345873,11.873095,...,71.441473,72.10115,72.044194,71.984621,71.837922,4.258490,2.033596,0.057334,7.211382,1.668266
min,2014.000000,11.550000,5.940000,6.190000,22.330000,12.260000,12.710000,13.420000,24.060000,60.630000,...,50.010000,50.06000,50.980000,50.060000,50.060000,5.000000,3.000000,0.300000,60.010000,2.000000
25%,2016.000000,69.770000,42.840000,34.390000,118.675000,69.420000,68.740000,65.130000,138.570000,71.000000,...,109.455000,111.02500,111.405000,110.245000,108.400000,9.055000,4.750000,0.350000,66.075000,3.590000
50%,2019.000000,96.720000,61.830000,47.760000,163.550000,98.520000,99.410000,95.910000,198.420000,82.030000,...,171.960000,170.87000,174.580000,170.560000,168.840000,12.470000,6.390000,0.400000,72.420000,4.960000
75%,2022.000000,137.460000,90.070000,68.720000,223.535000,137.480000,134.720000,135.945000,273.040000,92.340000,...,232.870000,237.29000,235.460000,236.230000,231.505000,16.140000,8.235000,0.450000,78.765000,6.345000
max,2024.000000,365.020000,278.510000,166.720000,582.960000,303.090000,353.440000,381.840000,686.780000,100.000000,...,299.890000,299.70000,299.870000,299.800000,299.360000,19.990000,10.000000,0.500000,84.950000,7.990000

In [27]:
#P8 menampilkan tabel penjulan februari


import pandas as pd

df = pd.read_csv('dataset_fiskal_97_hipoFull.csv')


#Tahun = df["Tahun"]
#Tahun.head(888)

#DBH_PAJAK = df["DBH_PAJAK"]
#DBH_PAJAK.head(700)

#DBH_SDA = df["DBH_SDA"]
#DBH_SDA.head(700)

In [26]:
# Menemukan nilai 'PAD' tertinggi dan tahunnya
max_pad_row = df.loc[df['PAD'].idxmax()]
highest_pad = max_pad_row['PAD']
year_of_highest_pad = max_pad_row['Tahun']

print(f"Nilai PAD tertinggi: {highest_pad}")
print(f"Tahun dengan PAD tertinggi: {year_of_highest_pad}")

Nilai PAD tertinggi: 686.78
Tahun dengan PAD tertinggi: 2021

In [25]:
# Menampilkan daftar berkas di direktori saat ini
import os
print(os.listdir('.'))

['.config', 'penjualan.csv', 'dataset_fiskal_97_hipoFull.csv', 'sample_data']